import { NextPage } from "next";
// import Head from "next/head";
// import Image from "next/image";
import React from "react";
// import Info from "components/info";
// import MenuPanel from "components/menu_panel";

export const getServerSideProps = async () => {
  return {
    redirect: {
      destination: "/main/student/profile",
      permanent: false,
    },
  };
};
export const Home: NextPage = () => {
  return <></>;
};

// return (
//   <div className="flex h-screen flex-col">
//     <Head>
//       <title>Fast Graduation</title>
//       <meta name="description" content="Generated by create next app" />
//       <link rel="icon" href="/favicon.ico" />
//     </Head>

//     <div className="gradient z-[1] h-[5%] blur-sm"></div>
//     <header className="container mx-auto">
//       <Image
//         src="/fastgrad.svg"
//         alt="fast graduate logo"
//         width={471 / 2}
//         height={180 / 2}
//         objectFit="cover"
//       />
//     </header>

//     <ul className="fast-text container mx-auto flex justify-end gap-x-1 px-3 md:gap-x-2 md:px-0">
//       <li>นักศึกษา</li>|<li>อาจารย์</li>
//     </ul>

//     <main className="mt-3 flex flex-grow flex-col px-3 md:px-0">
//       <Info />
//       <MenuPanel />
//     </main>

//     <footer className="h-max border text-black">
//       <div className="flex justify-end gap-x-4">
//         <Image
//           src="/fastgrad.svg"
//           alt="fast graduate logo"
//           width={471 / 4}
//           height={243 / 4}
//         />
//         <div className="my-4 w-2 flex-shrink rounded bg-gradient-to-b from-[rgba(251,162,131,0.53)] to-[rgba(204,171,216,0.85)]"></div>
//         <div className="fast-text w-36 break-words">
//           <p>ติดต่อผู้ดูแลระบบ</p>
//           <p>1234 ถ.คอนกรีต ต.บ้าน อ.เมือง จ.อิงแลนด์ 56789</p>
//           <p>053-xxx-xxx</p>
//           <p>reg@cnu.ca.th</p>
//         </div>
//       </div>
//     </footer>
//   </div>
// );

export default Home;
