import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import Info from "components/info";
import MenuPanel from "components/menu_panel";

export const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Fast Graduation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[5%] gradient blur-sm z-[1]"></div>
      <header className="container mx-auto">
        <Image
          src="/fastgrad.svg"
          alt="fast graduate logo"
          width={471 / 2}
          height={180 / 2}
          objectFit="cover"
        />
      </header>

      <ul className="container flex gap-x-1 justify-end px-3 mx-auto text-black md:gap-x-2 md:px-0">
        <li>นักศึกษา</li>|<li>อาจารย์</li>
      </ul>

      <main className="flex flex-col flex-grow px-3 mt-3 md:px-0">
        <Info />
        <MenuPanel />
      </main>

      <footer className="relative h-12 text-black border md:h-24">
        <div className="grid absolute right-0 grid-cols-2">
          <Image
            src="/fastgrad.svg"
            alt="fast graduate logo"
            width={471 / 4}
            height={243 / 4}
          />
          <div>
            <p>ติดต่อผู้ดูแลระบบ</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
