import "./globals.css";
import { Noto_Sans_Thai } from "@next/font/google";

const noto = Noto_Sans_Thai({
  subsets: ["thai"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${noto.className}`}>
      <body className="bg-white">{children}</body>
    </html>
  );
}
